apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-docusaurus-chart.fullname" . }}
  labels:
    app: {{ include "my-docusaurus-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "my-docusaurus-chart.name" . }}