replicaCount: 1

image:
  repository: personaldockerfile/docusaurus
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: docusaurus.example.com
      paths: ["/"]